.TH MODEM-CMD 1 "May 4, 2017"
.SH NAME
modem-cmd \- send arbitrary AT commands to your modem
.SH SYNOPSIS
.B modem-cmd
.RI "[ device ] [ command ]"
.SH DESCRIPTION
This manual page documents briefly the
.B modem-cmd
commands.
.PP
\fBmodem-cmd\fP can be used to send arbitrary AT commands to a modem device over a serial line. This means it can be used as a phone dialer.
.SH USAGE
.LP
modem-cmd /dev/ttyUSB0 ATDT123456
.SH AUTHOR
modem-cmd was written by YuLun Shih <shih@yulun.me>.
